apiVersion: kobefederator.kobe.com/v1alpha1
kind: KobeFederator
metadata:
  name: semagrow
spec:
  image: semagrow/semagrow
  imagePullPolicy: Always
  port: 8080
  confFromFileImage: kostbabis/semagrow-init #matadata file image from dump or endpoint
  inputFileDir: /sevod-scraper/input
  outputFileDir: /sevod-scraper/output
  confImage: kostbabis/semagrow-init-all #init image metadata from many
  inputDir: /kobe/input
  outputDir: /kobe/output
  fedConfDir: /etc/default/semagrow
  sparqlEnding: /SemaGrow/sparql


